version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/hs-web-phishing-detection
file_exists_behavior: OVERWRITE # file already exists at this location 에러 방지
permissions:
  - object: /home/ubuntu/web-phishing-detection/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 500
      runas: ubuntu